apiVersion: sources.knative.dev/v1beta1
kind: KafkaSource
metadata:
  name: measures-kafka-source
spec:
  consumerGroup: knative-group
  bootstrapServers:
  - my-cluster-kafka-bootstrap.kafka:9092
  topics:
  - measures 
  sink:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: processor

